# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HaidressingSalon' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod 'RESideMenu'
  # Pods for HaidressingSalon

  target 'HaidressingSalonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HaidressingSalonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
